# name of your github action
name: CI
on:
  push:
    branches:
    # this will run on the electron branch
      - dev
jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@dev
      with:
        ref: feature/github-actions        
    - uses: actions/setup-node@dev
      with:
        node-version: 16.x
    - name: see directory
      run: ls